### ISSUE TITLE
Add support for iOS 10 emojis 

### ISSUE THREAD

**Issue by deAngelisAlex** [DSteve595/EmojiSwitcher#13]
Hi @DSteve595,

Could you add support for iOS 10 emojis please? 

Thank you,
Alexandre de Angelis

**Comment by DSteve595** [comment]
Already added.

**Comment by deAngelisAlex** [comment]
You did add iOS 9, but not iOS 10, sorry :)

**Comment by DSteve595** [comment]
Check again?
