### ISSUE TITLE
EmojiOne : Update !

### ISSUE THREAD

**Issue by HorlogeSkynet** [DSteve595/EmojiSwitcher#18]
Hello there,

Is this app still maintained ? If that's the case could you upgrade EmojiOne ?
On the official repository there are [some new releases](https://github.com/emojione/emojione/releases) since the v2.2.7 !

Great app, thanks bye 👋

--> One more question : Have you planned to get rid of Google libraries so as to publish it on F-Droid repositories ?

EDIT : Oh well, 'didn't see the other (closed) issues about that... So my first question makes definitely sense

**Comment by DSteve595** [comment]
Sorry, I no longer maintain this app.

**Comment by HorlogeSkynet** [comment]
No problem, thanks for clarifying it 👌
Bye 👋

**Comment by HorlogeSkynet** [comment]
For people root-ed with Magisk, I'd like to set a link there for them (if you don't mind) to a module with a newer version of EmojiOne : https://forum.xda-developers.com/apps/magisk/module-emoji-one-t3477911

Sources here : https://github.com/Magisk-Modules-Repo/Magisk-EmojiOne-systemless

Thanks,
Bye 👋
