### ISSUE TITLE
Marshmallow

### ISSUE THREAD

**Issue by firatciftci** [DSteve595/EmojiSwitcher#2]
I'm on Android 6.0 (Nexus 6) and I can't switch to another emoji type, only Lollipop.

**Comment by DSteve595** [comment]
I don't have any devices with Marshmallow to work with :(

Will fix as soon as I can get ahold of one.

**Comment by firatciftci** [comment]
Oh ok, I can always be a beta tester if needed. :)

**Comment by DSteve595** [comment]
Thanks for the offer, but I'd need to poke around one myself to see what's
changed before I can fix it.
