### ISSUE TITLE
New emoji IOS

### ISSUE THREAD

**Issue by gabriellmgomes** [DSteve595/EmojiSwitcher#3]
good night, you will add the new emojis that are in the new version of IOS?

**Comment by DSteve595** [comment]
There's a test version of the iOS 9.1 emoji up.

**Comment by gabriellmgomes** [comment]
These new Emoji?  ![Emoji?](http://s2.glbimg.com/Q90apvco1LhHnVaFK-QW7Ybb9jg=/695x0/s.glbimg.com/po/tt2/f/original/2015/09/11/imagem18.jpg)

**Comment by DSteve595** [comment]
Pretty sure they're in the set.
